--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Muqsit/AsyncIterator
build-by-default: true
branches:
- master
- pm5
projects:
  AsyncIterator:
    path: ""
    model: virion
    type: library
...
